### ISSUE TITLE
[other] Unexplained - '(Commit 2cbd46ed1b9a50eeb517126ba034d78ee885f63b)' added to has_source line

### ISSUE THREAD

**Issue by akumar21** [SoftwareEngineeringToolDemos/ICSE-2013-DRC#2]
Not sure if this is a issue or not but I don't understand the information presented here, requesting the tool owner to add some details as to what are we suppose to do with this.

**Comment by jayantdhawan** [comment]
Earlier, the original source code was referenced as a commit ID in the README file, i.e. the last commit just before the one that made the tool workable was referenced. Now, a new directory has been added - _projects-original_ - that contains the original, unmodified projects (source code) as provided by authors. README has been updated.
